const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const ROOT=__dirname, DATA=path.join(ROOT,"data","site.json"), PORT=Number(process.env.PORT)||10000;
const sessions=new Map();
function load(){try{return JSON.parse(fs.readFileSync(DATA,"utf8"))}catch{return {}}}
function save(d){fs.mkdirSync(path.dirname(DATA),{recursive:true});fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function send(res,status,data,type="application/json"){res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});res.end(type.includes("json")?JSON.stringify(data):data)}
function body(req){return new Promise((resolve,reject)=>{let s="";req.on("data",c=>{s+=c;if(s.length>2e6)req.destroy()});req.on("end",()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on("error",reject)})}
function auth(req){const t=(req.headers.authorization||"").replace(/^Bearer\s+/,"");return t&&sessions.has(t)}
function id(p="PN"){return p+"-"+Date.now().toString(36)+"-"+crypto.randomBytes(3).toString("hex")}
function serve(req,res){let u=new URL(req.url,"http://x"),file=u.pathname==="/"?"/index.html":u.pathname==="/admin"||u.pathname==="/admin/"?"/admin.html":u.pathname;if(file.includes(".."))return send(res,403,{error:"Forbidden"});let f=path.join(ROOT,file);fs.readFile(f,(e,b)=>{if(e)return send(res,404,{error:"Not found"});let ext=path.extname(f),types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".svg":"image/svg+xml",".json":"application/json"};send(res,200,b,types[ext]||"application/octet-stream")})}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,"http://x"),d=load();
if(u.pathname==="/api/login"&&req.method==="POST"){let b=await body(req);if(b.email===(process.env.ADMIN_EMAIL||"admin@purenari.com")&&b.password===(process.env.ADMIN_PASSWORD||"change-me")){let t=crypto.randomBytes(24).toString("hex");sessions.set(t,Date.now());return send(res,200,{token:t})}return send(res,401,{error:"Invalid credentials"})}
if(u.pathname==="/api/logout"&&req.method==="POST"){let t=(req.headers.authorization||"").replace(/^Bearer\s+/,"");sessions.delete(t);return send(res,200,{ok:true})}
if(u.pathname==="/api/site"&&req.method==="GET")return send(res,200,{...d,orders:undefined,leads:undefined});
if(u.pathname==="/api/reviews"&&req.method==="GET")return send(res,200,(d.reviews||[]).filter(x=>x.approved));
if(u.pathname==="/api/reviews"&&req.method==="POST"){let b=await body(req);if(!b.name||!b.text)return send(res,400,{error:"Name and review are required"});let r={id:id("REV"),name:String(b.name).slice(0,80),rating:Math.min(5,Math.max(1,Number(b.rating)||5)),text:String(b.text).slice(0,1000),image:b.image||"",date:new Date().toISOString().slice(0,10),approved:false};d.reviews=[r,...(d.reviews||[])];save(d);return send(res,201,{ok:true,message:"Review submitted for approval"})}
if(u.pathname==="/api/orders"&&req.method==="POST"){let b=await body(req);if(!b.name||!b.phone||!b.address||!Array.isArray(b.items)||!b.items.length)return send(res,400,{error:"Complete order details are required"});let o={id:id("PNO"),name:b.name,phone:b.phone,address:b.address,items:b.items,payment:b.payment||"COD",transactionId:b.transactionId||"",total:Number(b.total)||0,status:"Pending",createdAt:new Date().toISOString()};d.orders=[o,...(d.orders||[])];save(d);return send(res,201,{ok:true,orderId:o.id})}
if(u.pathname==="/api/leads"&&req.method==="POST"){let b=await body(req);d.leads=[{id:id("LEAD"),...b,createdAt:new Date().toISOString()},...(d.leads||[])];save(d);return send(res,201,{ok:true})}
if(u.pathname==="/api/chat"&&req.method==="POST"){let b=await body(req),q=String(b.message||"").toLowerCase(),reply="I can help with products, usage, orders, delivery or an agent. Ask me anything about Pure Nari.";if(/agent|human|মানুষ|কথা/.test(q))reply="Sure — tap the Contact Agent button above me to reach our beauty agent.";else if(/delivery|ডেলিভারি/.test(q))reply="We accept orders for delivery across Bangladesh. Final delivery details can be confirmed by the agent.";else if(/use|usage|ব্যবহার|কিভাবে/.test(q))reply="Open any product and check “How to use” for its editable usage guidance.";else if(/order|অর্ডার/.test(q))reply="You can add a product to cart and checkout, or ask me to guide you through an order.";else if(/serum|cleanser|toner|sunscreen|moisturizer|essence|mask|lip/.test(q))reply="Tell me your skin concern or the product/category name and I’ll point you to the relevant Pure Nari collection.";return send(res,200,{reply})}
if(u.pathname==="/api/admin/stats"&&req.method==="GET"&&auth(req))return send(res,200,{orders:d.orders?.length||0,revenue:(d.orders||[]).reduce((s,o)=>s+(Number(o.total)||0),0),products:d.products?.length||0,reviews:d.reviews?.length||0,leads:d.leads?.length||0});
if(u.pathname==="/api/admin/orders"&&req.method==="GET"&&auth(req))return send(res,200,d.orders||[]);
if(u.pathname==="/api/admin/reviews"&&req.method==="GET"&&auth(req))return send(res,200,d.reviews||[]);
if(u.pathname==="/api/admin/leads"&&req.method==="GET"&&auth(req))return send(res,200,d.leads||[]);
let m=u.pathname.match(/^\/api\/admin\/(orders|reviews|leads)\/([^/]+)$/);if(m&&req.method==="PATCH"&&auth(req)){let b=await body(req),arr=d[m[1]]||[],i=arr.findIndex(x=>x.id===m[2]);if(i<0)return send(res,404,{error:"Not found"});arr[i]={...arr[i],...b};d[m[1]]=arr;save(d);return send(res,200,{ok:true})}
if(u.pathname==="/api/site"&&req.method==="PUT"&&auth(req)){let b=await body(req);d={...d,...b};save(d);return send(res,200,{ok:true})}
serve(req,res)}catch(e){send(res,500,{error:"Server error"})}});
server.listen(PORT,"0.0.0.0",()=>console.log("PURE NARI running on "+PORT));